apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  containers:
  - image: {{ .Values.containers.image }}
    name: {{ .Values.name }}
    imagePullPolicy: IfNotPresent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
