apiVersion: v1
kind: Service
metadata:
  labels:
   name: {{ .Values.name }}
  name: "{{ .Values.name }}-svc"
spec:
  type: NodePort
  selector:
    name: {{ .Values.name }}
  ports:
    - port: {{ .Values.ports.port }}
      name: {{ .Values.ports.name }}
      targetPort: {{ .Values.ports.targetPort }}
      nodePort: {{ .Values.ports.nodePort }}
