apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name:  "{{ .Values.name }}-svc-monitor"
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: {{ .Values.ports.name }}
  selector:
    matchLabels:
      name: {{ .Values.name }}
